### PR TITLE
release version

### PR DESCRIPTION
**Pull request by kaisbaccour**

### CODE REVIEW

**Review by jaeaster — APPROVED** [review]
We can't change the name on the bucket right?

**Comment by jaeaster** [comment]
Also, do we need to bump the version in the Cargo.toml ?

**Comment by kaisbaccour** [comment]
> We can't change the name on the bucket right?

What name do you prefer?

**Comment by kaisbaccour** [comment]
> Also, do we need to bump the version in the Cargo.toml ?

Just did it now

**Pull request merged**
